### ISSUE TITLE
Undefined method add_builtin_type for Psyc ( NoMethodError)

### ISSUE THREAD

**Issue by rcoproc** [RailsApps/rails_apps_composer#351]
Hi, 

I run the comamnd in bash
@Ricardo Dir ~/Documents/RAILS/Otica :[ Tue Jan 05-11:44 AM]
[Ruby 2.2.2] rails_app_composer new .

an i have the problem:

/Users/Ricardo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/ordered_hash.rb:3:in `<top (required)>': undefined method `add_builtin_type' for Psych:Module (NoMethodError)
        from /Users/Ricardo/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
        from /Users/Ricardo/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
        from /Users/Ricardo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rails_apps_composer-3.1.4/lib/rails_wizard/config.rb:1:in `<top (required)>'
        from /Users/Ricardo/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /Users/Ricardo/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /Users/Ricardo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rails_apps_composer-3.1.4/lib/rails_wizard/recipe.rb:1:in `<top (required)>'
        from /Users/Ricardo/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /Users/Ricardo/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /Users/Ricardo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rails_apps_composer-3.1.4/lib/rails_wizard.rb:2:in `<top (required)>'
        from /Users/Ricardo/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /Users/Ricardo/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /Users/Ricardo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rails_apps_composer-3.1.4/lib/rails_wizard/command.rb:1:in `<top (required)>'
        from /Users/Ricardo/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /Users/Ricardo/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /Users/Ricardo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rails_apps_composer-3.1.4/bin/rails_apps_composer:5:in `<top (required)>'
        from /Users/Ricardo/.rbenv/versions/2.2.2/bin/rails_apps_composer:23:in `load'
        from /Users/Ricardo/.rbenv/versions/2.2.2/bin/rails_apps_composer:23:in `<main>'

**Comment by rcoproc** [comment]
The problem is HERE

yaml.rb
YAML = Psych # :nodoc:

The YAML object has no method 'add_builtin_type'
but in version 2.0.08 Psych are there to see .:

psych.rb

 # :stopdoc:
  @domain_types = {}
  def self.add_domain_type domain, type_tag, &block
    key = ['tag', domain, type_tag].join ':'
    @domain_types[key] = [key, block]
    @domain_types["tag:#{type_tag}"] = [key, block]
  end

  def self.add_builtin_type type_tag, &block
    domain = 'yaml.org,2002'
    key = ['tag', domain, type_tag].join ':'
    @domain_types[key] = [key, block]
  end

  def self.remove_type type_tag
    @domain_types.delete type_tag
  end



*** LOCAL GEMS ***

psych (2.0.17, 2.0.8)
