### ISSUE TITLE
uninitialized constant RailsWizard::Command::Tempfile (NameError)

### ISSUE THREAD

**Issue by shaoyangyu** [RailsApps/rails_apps_composer#363]
Hello, 

No one else has NameError issue like this? :) 

ruby 2.3.1 p112

ruby-2.3.1  branch:master o:$ rc new haha -r core
Would you like to skip Test::Unit? (yes for RSpec) (y/n) y
Would you like to skip Active Record? (yes for MongoDB) (y/n) y
What gem would you like to add? (blank to finish) 
/home/shaoyang/.rvm/gems/ruby-2.3.1/gems/rails_apps_composer-3.1.27/lib/rails_wizard/command.rb:179:in `run_template': uninitialized constant RailsWizard::Command::Tempfile (NameError)
Did you mean?  RailsWizard::Template
        from /home/shaoyang/.rvm/gems/ruby-2.3.1/gems/rails_apps_composer-3.1.27/lib/rails_wizard/command.rb:25:in `new'
        from /home/shaoyang/.rvm/gems/ruby-2.3.1/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from /home/shaoyang/.rvm/gems/ruby-2.3.1/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/shaoyang/.rvm/gems/ruby-2.3.1/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from /home/shaoyang/.rvm/gems/ruby-2.3.1/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        from /home/shaoyang/.rvm/gems/ruby-2.3.1/gems/rails_apps_composer-3.1.27/bin/rails_apps_composer:7:in `<top (required)>'
        from /home/shaoyang/.rvm/gems/ruby-2.3.1/bin/rails_apps_composer:23:in `load'
        from /home/shaoyang/.rvm/gems/ruby-2.3.1/bin/rails_apps_composer:23:in `<main>'

**Comment by shaoyangyu** [comment]
After require 'tempfile', everything works well.
